Allow --version to overwrite addon version
home-assistant/builder pull request #62
Opened 2020-11-26 13:08 UTC by einschmidt

### Goal
Allow to set the build version for add-ons via the --version or -v parameter.

### Use-case
Using the GitHub actions, I want to be able to use different actions for different purposes, and different results. For example:
- Action 1 builds and uploads the addon release docker files. This is currently possible
- Action 2 builds a dev/edge docker image that is using a specific tag/version which is different to the version of the stable addon, and which is not latest. 

### Change
1. Handover version variable when building add-on
2. Read the version from config.json only when handover variable is empty
3. Don't declare the version variable for addon build

### desired example config
```
- name: Publish
  uses: home-assistant/builder@master
  with:
   args: |
    --all \
    --target /data \
    --version test \
    --docker-hub userspace-name
```

2020-11-26 13:08 UTC, homeassistant commented
Hi @einschmidt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;builder#62).

Once you do that we will be able to review and accept this pull request.

Thanks!

2020-11-26 13:11 UTC, homeassistant commented
Hi @einschmidt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;builder#62).

Once you do that we will be able to review and accept this pull request.

Thanks!

2020-12-01 09:11 UTC, ludeeus requested changes
This does not enable `--version` for addons furthermore, this will break the build if `--version` is passed with `--addon` since `version` in the `build_addon` function will be blank.

2020-12-01 17:45 UTC, einschmidt commented
Thanks for the review @ludeeus. I reviewed the variables and changed the PR accordingly.
Happy to receive another review. :-)

2020-12-07 09:15 UTC, ludeeus approved these changes

2020-12-07 09:16 UTC, merged

2021-01-23 13:00 UTC, tjorim commented
Nice improvement, no more `sed` in the config.json to adjust the version 🎉